
/**
 * Interface definition for the diagnostic report generated by runDiagnostics.
 */
export interface DiagnosticReport {
    /** ISO timestamp of when the report was generated. */
    timestamp: string;
    /** Browser User Agent string. */
    userAgent: string;
    /** Map of environment variable names to boolean presence status. */
    envCheck: Record<string, boolean>;
    /** Network connectivity status. */
    online: boolean;
    /** Storage availability status. */
    storage: {
        localStorage: boolean;
        sessionStorage: boolean;
        cookies: boolean;
    };
}

/**
 * Runs a suite of diagnostic checks to help troubleshoot client-side issues.
 * Checks for:
 * - Environment variables (Firebase config).
 * - Browser storage availability (LocalStorage, SessionStorage, Cookies).
 * - Network connectivity.
 *
 * @returns {DiagnosticReport} A structured object containing diagnostic data.
 */
export const runDiagnostics = (): DiagnosticReport => {
    // Initialize the report structure with basic info (timestamp, UA, online status)
    const report: DiagnosticReport = {
        timestamp: new Date().toISOString(),
        userAgent: navigator.userAgent,
        envCheck: {},
        online: navigator.onLine,
        storage: {
            localStorage: false,
            sessionStorage: false,
            cookies: navigator.cookieEnabled // Check if cookies are enabled
        }
    };

    // Define the list of critical environment variables required for the app to function
    const requiredEnv = [
        'VITE_FIREBASE_API_KEY',
        'VITE_FIREBASE_AUTH_DOMAIN',
        'VITE_FIREBASE_PROJECT_ID'
    ];

    // Check for the existence of each environment variable
    requiredEnv.forEach(key => {
        // We use import.meta.env, assuming Vite as the build tool.
        // Double negation converts the value (or undefined) to a strict boolean.
        report.envCheck[key] = !!import.meta.env[key];
    });

    // Check LocalStorage availability
    try {
        // Attempt to write and remove a test item.
        // This will throw an error if Storage is full or disabled (e.g., Safari Private Mode).
        localStorage.setItem('__test__', '1');
        localStorage.removeItem('__test__');
        report.storage.localStorage = true;
    } catch (e) { /* Storage not available */ }

    // Check SessionStorage availability
    try {
        // Similar test for SessionStorage.
        sessionStorage.setItem('__test__', '1');
        sessionStorage.removeItem('__test__');
        report.storage.sessionStorage = true;
    } catch (e) { /* Storage not available */ }

    return report;
};

/**
 * Formats the diagnostic report into a human-readable string for sharing.
 *
 * @param {DiagnosticReport} report - The report object generated by runDiagnostics.
 * @returns {string} A formatted text block suitable for clipboard copy/paste.
 */
export const formatReport = (report: DiagnosticReport): string => {
    // Start with Header
    let output = `[Diagnostic Report - ${report.timestamp}]\n`;

    // Add Basic Info
    output += `User Agent: ${report.userAgent}\n`;
    output += `Online: ${report.online ? '✅' : '❌'}\n\n`;

    // Add Environment Checks
    output += `Environment Variables:\n`;
    Object.entries(report.envCheck).forEach(([key, exists]) => {
        output += `  ${exists ? '✅' : '❌'} ${key}\n`;
    });

    // Add Storage Checks
    output += `\nStorage:\n`;
    output += `  ${report.storage.localStorage ? '✅' : '❌'} LocalStorage\n`;
    output += `  ${report.storage.sessionStorage ? '✅' : '❌'} SessionStorage\n`;
    output += `  ${report.storage.cookies ? '✅' : '❌'} Cookies\n`;

    return output;
};
